-- Eager: fff.nvim needs to initialize its event loop integration at startup
vim.pack.add({ "https://github.com/dmtrKovalenko/fff.nvim" })

local map = vim.keymap.set
map("n", "<leader>ff", function() require("fff").find_files() end, { desc = "Find Files" })
map("n", "<leader>fg", function() require("fff").live_grep() end, { desc = "Live Grep" })
map("n", "<leader>fr", function() require("fff").find_files() end, { desc = "Find Files (recent)" })
map("n", "<leader>fc", function()
    require("fff").find_files_in_dir(vim.fn.stdpath("config"))
end, { desc = "Find Config File" })
map("n", "<leader>sg", function() require("fff").live_grep() end, { desc = "Grep" })
map("n", "<leader>sw", function()
    require("fff").live_grep({ query = vim.fn.expand("<cword>") })
end, { desc = "Grep Word (cword)" })
map("n", "<leader>sW", function()
    require("fff").live_grep({ query = vim.fn.expand("<cWORD>") })
end, { desc = "Grep Word (cWORD)" })
map("v", "<leader>sw", function()
    vim.cmd('noau normal! "vy')
    require("fff").live_grep({ query = vim.fn.getreg("v") })
end, { desc = "Grep Selection" })
