import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
padding = { x = 5, y = 5 }
decorations_theme_variant = "Dark"
opacity = 0.9
dynamic_padding = true

[font]
normal = { family = "Iosevka Nerd Font Mono", style = "Regular"}
size = 18

[env]
TERM = "xterm-256color"
