/**
 * skill-router-parity.test.ts — parity test against Python rule_probs oracle.
 *
 * Run: npx tsx --test pi/.pi/agent/extensions/skill-router-parity.test.ts
 *
 * Requires the local parity file at:
 *   ~/.local/share/pi-decision-eval/data/labels/ts_parity_149.jsonl
 *
 * If the file is absent, all tests are skipped (CI-safe, no session text in repo).
 * The file is generated by:
 *   python3 ~/.local/share/pi-decision-eval/harness/export_ts_vectors.py
 */

import { describe, it } from "node:test";
import * as assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import {
  scorePrompt,
  isExplicitTurn,
  loadCatalog,
} from "./skill-router.ts";

const PARITY_FILE = join(
  process.env.HOME ?? "",
  ".local/share/pi-decision-eval/data/labels/ts_parity_149.jsonl",
);

const catalog = loadCatalog();
const allNames = [...catalog.keys()];

describe("parity with Python rule_probs (149 labeled turns)", () => {
  if (!existsSync(PARITY_FILE)) {
    it("SKIPPED: parity file not found (run export_ts_vectors.py)", { skip: true }, () => {});
    return;
  }

  const lines = readFileSync(PARITY_FILE, "utf-8").trim().split("\n");
  const vectors: Array<{ turn_id: string; prompt: string; hits: Record<string, number> }> =
    lines.map((l) => JSON.parse(l));

  for (const vec of vectors) {
    it(`${vec.turn_id}`, () => {
      // If it's explicit, the Python oracle still scores it but the router skips.
      // The parity test verifies the scoring function itself, ignoring explicit detection.
      const scores = scorePrompt(vec.prompt, allNames);

      // Compare: every hit in Python should be in TypeScript, and vice versa
      const tsHits: Record<string, number> = {};
      for (const [name, score] of scores) {
        if (score > 0) tsHits[name] = score;
      }

      const pyHits = vec.hits;

      // Check all Python hits are present in TypeScript
      for (const [name, pyScore] of Object.entries(pyHits)) {
        const tsScore = tsHits[name];
        assert.ok(
          tsScore !== undefined,
          `Python hit ${name}=${pyScore} missing in TypeScript (turn ${vec.turn_id})`,
        );
        assert.equal(
          tsScore,
          pyScore,
          `${name}: Python=${pyScore}, TypeScript=${tsScore} (turn ${vec.turn_id})`,
        );
      }

      // Check no extra TypeScript hits
      for (const [name, tsScore] of Object.entries(tsHits)) {
        assert.ok(
          name in pyHits,
          `TypeScript hit ${name}=${tsScore} not in Python (turn ${vec.turn_id})`,
        );
      }

    });
  }

  // Summary is reported by the test runner
});
