{ config, lib, ... }:

let
  cfg = config.programs.ai-agents.opencode;
  profiles = cfg.resolvedProfiles;
in
lib.mkIf (config.programs.ai-agents.enable && profiles != { }) {
  xdg.configFile."direnv/lib/opencode.sh".text = ''
    # Auto-generated by nix-darwin — do not edit manually
    use_opencode_profile() {
      if [ $# -eq 0 ]; then
        echo "usage: use opencode_profile <profile...>" >&2
        echo "available profiles: ${lib.concatStringsSep " " (builtins.attrNames profiles)}" >&2
        return 1
      fi

      local _paths=()
      for _profile in "$@"; do
        case "$_profile" in
          ${lib.concatStringsSep "\n          " (lib.mapAttrsToList (name: meta:
            "${name}) _paths+=(\"${meta.path}\") ;;"
          ) profiles)}
          *) echo "use_opencode_profile: unknown profile '$_profile'" >&2; return 1 ;;
        esac
      done

      # Accumulate across source_up calls.
      # ponytail: colon delimiter assumes Nix store paths; breaks if paths contain ':'
      if [ -n "''${_OPENCODE_PROFILE_PATHS:-}" ]; then
        IFS=: read -ra _existing <<< "$_OPENCODE_PROFILE_PATHS"
        _paths=("''${_existing[@]}" "''${_paths[@]}")
      fi
      export _OPENCODE_PROFILE_PATHS=$(IFS=:; echo "''${_paths[*]}")

      # Build OPENCODE_CONFIG_CONTENT JSON from full accumulated path list
      local _json='{"skills":{"paths":['
      local _first=true
      for _p in "''${_paths[@]}"; do
        if [ "$_first" = false ]; then _json+=","; fi
        local _pe="''${_p//\\/\\\\}"; _pe="''${_pe//\"/\\\"}"
        _json+="\"$_pe\""
        _first=false
      done
      _json+=']}}'
      export OPENCODE_CONFIG_CONTENT="$_json"
    }
  '';
}
