{ config, lib, pkgs, ... }:

let
  cfg = config.programs.ai-agents.opencode;
  profiles = cfg.resolvedProfiles;

  # All dirs across all profiles (for nesting detection)
  allProfileDirs = lib.concatLists (
    lib.mapAttrsToList (_name: meta: meta.dirs) profiles
  );

  # Expand ~ to home directory for comparison
  expandHome = dir: lib.strings.replaceStrings [ "~" ] [ config.home.homeDirectory ] dir;

  # A dir is nested if any OTHER dir (across all profiles) is a strict prefix of it
  isNested = dir:
    let expanded = expandHome dir;
    in lib.any (other:
      let expandedOther = expandHome other;
      in other != dir && lib.hasPrefix (expandedOther + "/") expanded
    ) allProfileDirs;

  # Build dir -> [profile names] mapping (handles dirs shared across profiles)
  dirToProfiles = lib.foldlAttrs (acc: profileName: meta:
    lib.foldl (a: dir:
      let existing = a.${dir} or [];
      in a // { ${dir} = existing ++ [ profileName ]; }
    ) acc meta.dirs
  ) {} profiles;

  # Generate one .envrc per dir, listing all applicable profiles
  envrcFiles = lib.mapAttrs' (dir: profileNames:
    let
      expandedDir = expandHome dir;
      content = (lib.optionalString (isNested dir) "source_up\n")
        + "use opencode_profile ${lib.concatStringsSep " " profileNames}";
    in lib.nameValuePair
      "${lib.removePrefix (config.home.homeDirectory + "/") expandedDir}/.envrc"
      { text = content; }
  ) dirToProfiles;
in
lib.mkIf (config.programs.ai-agents.enable && profiles != { }) {
  xdg.configFile."direnv/lib/opencode.sh".text = ''
    # Auto-generated by nix-darwin — do not edit manually
    use_opencode_profile() {
      if [ $# -eq 0 ]; then
        echo "usage: use opencode_profile <profile...>" >&2
        echo "available profiles: ${lib.concatStringsSep " " (builtins.attrNames profiles)}" >&2
        return 1
      fi

      local _paths=()
      for _profile in "$@"; do
        case "$_profile" in
          ${lib.concatStringsSep "\n          " (lib.mapAttrsToList (name: meta:
            "${name}) _paths+=(\"${meta.path}\") ;;"
          ) profiles)}
          *) echo "use_opencode_profile: unknown profile '$_profile'" >&2; return 1 ;;
        esac
      done

      # Accumulate across source_up calls.
      # ponytail: colon delimiter assumes Nix store paths; breaks if paths contain ':'
      if [ -n "''${_OPENCODE_PROFILE_PATHS:-}" ]; then
        IFS=: read -ra _existing <<< "$_OPENCODE_PROFILE_PATHS"
        _paths=("''${_existing[@]}" "''${_paths[@]}")
      fi
      export _OPENCODE_PROFILE_PATHS=$(IFS=:; echo "''${_paths[*]}")

      # Build OPENCODE_CONFIG_CONTENT JSON from full accumulated path list
      local _json='{"skills":{"paths":['
      local _first=true
      for _p in "''${_paths[@]}"; do
        if [ "$_first" = false ]; then _json+=","; fi
        local _pe="''${_p//\\/\\\\}"; _pe="''${_pe//\"/\\\"}"
        _json+="\"$_pe\""
        _first=false
      done
      _json+=']}}'
      export OPENCODE_CONFIG_CONTENT="$_json"
    }
  '';

  home.file = envrcFiles;

  home.activation.allowOpencodeProfileEnvrc = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    ${lib.concatMapStrings (dir:
      let expandedDir = lib.strings.replaceStrings [ "~" ] [ "$HOME" ] dir;
      in ''
        if [ -f "${expandedDir}/.envrc" ]; then
          $DRY_RUN_CMD ${pkgs.direnv}/bin/direnv allow "${expandedDir}/.envrc" || true
        fi
      ''
    ) allProfileDirs}
  '';
}
