{ config, lib, ... }:

lib.mkIf (config.programs.ai-agents.enable && builtins.elem "pi" config.programs.ai-agents.agents) {
  xdg.configFile."direnv/lib/pi.sh".text = ''
    # Auto-generated by nix-darwin — do not edit manually
    use_pi_profile() {
      if [ $# -eq 0 ]; then
        echo "usage: use pi_profile <profile...>" >&2
        return 1
      fi

      for _profile in "$@"; do
        local _profile_dir="$HOME/.config/opencode/skill-profiles/$_profile"
        if [ -d "$_profile_dir" ]; then
          # Accumulate across source_up calls.
          # ponytail: colon delimiter assumes paths without ':'; matches opencode convention
          if [ -n "''${PI_SKILL_PATHS:-}" ]; then
            export PI_SKILL_PATHS="$PI_SKILL_PATHS:$_profile_dir"
          else
            export PI_SKILL_PATHS="$_profile_dir"
          fi
        else
          echo "use_pi_profile: profile directory not found: $_profile_dir" >&2
        fi
      done
    }
  '';
}
